apiVersion: v1
kind: Service
metadata:
  name: grpc-backend
  namespace: {{ .Values.Namespace }}
  labels:
    app: grpc-backend
  annotations:
    # Enable automatic monitoring of all instances when Prometheus is running in the cluster.
    prometheus.io/scrape: "true"
    prometheus.io/path: "_status/vars"
    prometheus.io/port: "8080"
spec:
  ports:
  - port: {{ .Values.GrpcPort }}
    targetPort: {{ .Values.GrpcPort }}
    name: grpc
  selector:
    app: grpc-backend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-backend
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-backend
    spec:
      volumes:
      - name: client-certs
        secret:
          secretName: cockroachdb.client.root
          defaultMode: 256
      - name: ca-cert
        secret:
          secretName: cockroachdb.ca.crt
          defaultMode: 256
      - name: public-certs
        secret:
          secretName: dss.public.certs
          defaultMode: 256
      containers:
      - name: grpc-backend
        image: {{ .Values.BackendImage }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.GrpcPort }}
          name: grpc
        volumeMounts:
        - name: client-certs
          mountPath: /cockroach-certs/client.root.key
          subPath: client.root.key
        - name: client-certs
          mountPath: /cockroach-certs/client.root.crt
          subPath: client.root.crt
        - name: public-certs
          mountPath: /public-certs
        - name: ca-cert
          mountPath: /cockroach-certs/ca.crt
          subPath: ca.crt
        args:
          - grpc-backend
          - -addr=:{{ .Values.GrpcPort }}
          - -cockroach_host=cockroachdb-balanced.{{ .Values.Namespace }}
          - -cockroach_port={{ .Values.CockroachPort }}
          - -cockroach_ssl_mode=verify-full
          - -cockroach_user=root
          - -cockroach_ssl_dir=/cockroach-certs
          - -public_key_file=/public-certs/{{ .Values.JWTPublicCert }}
          - -dump_requests
          - -jwt_audience={{ .Values.Hostnames.Frontend }}
